
import { GoogleGenAI } from "@google/genai";

// Assume process.env.API_KEY is configured in the environment
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you might have a more robust way to handle this,
  // but for this context, we'll throw an error if the key is missing.
  console.error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Generates an ad creative image using Gemini's imagen-4.0 model.
 * @param prompt - The text prompt describing the desired image.
 * @param aspectRatio - The aspect ratio for the generated image.
 * @returns A promise that resolves to a base64 encoded data URL (e.g., "data:image/jpeg;base64,...").
 */
export const generateAdCreative = async (prompt: string, aspectRatio: '16:9' | '9:16' | '1:1' | '4:3' | '3:4' = '16:9'): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: aspectRatio,
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating ad creative:", error);
    // Re-throw the error to be handled by the calling component
    throw new Error("Failed to communicate with the image generation service.");
  }
};